import 'dotenv/config'
import { db } from '../client'
import { materialReference } from '../schema'

const MATERIALS = [
  {
    name: 'PLA',
    variants: ['Standard', 'Basic'],
    nozzle_min: 190, nozzle_max: 230, nozzle_recommended: 215,
    bed_min: 50, bed_max: 60, bed_recommended: 55,
    requires_enclosure: false, dry_before_print: false,
    drying_temp_c: null, drying_hours: null,
    cooling_fan: 'high',
    density_g_cm3: '1.240', tensile_strength_mpa: 50, heat_resistance_c: 60,
    uv_resistant: false, food_safe: false, is_abrasive: false,
    moisture_sensitivity_days: 7,
    beginner_tip: 'Best starting material. Prints at low temps, minimal warping, no enclosure needed. If corners lift, add a brim.',
  },
  {
    name: 'PLA+',
    variants: ['PLA Plus', 'PLA Pro'],
    nozzle_min: 200, nozzle_max: 235, nozzle_recommended: 220,
    bed_min: 55, bed_max: 65, bed_recommended: 60,
    requires_enclosure: false, dry_before_print: false,
    drying_temp_c: null, drying_hours: null,
    cooling_fan: 'high',
    density_g_cm3: '1.240', tensile_strength_mpa: 55, heat_resistance_c: 65,
    uv_resistant: false, food_safe: false, is_abrasive: false,
    moisture_sensitivity_days: 7,
    beginner_tip: 'Tougher and slightly more flexible than standard PLA. Run 5–10°C hotter. Great all-rounder for functional parts.',
  },
  {
    name: 'PETG',
    variants: ['PETG Basic', 'PETG HF'],
    nozzle_min: 230, nozzle_max: 250, nozzle_recommended: 240,
    bed_min: 70, bed_max: 85, bed_recommended: 80,
    requires_enclosure: false, dry_before_print: true,
    drying_temp_c: 65, drying_hours: '4.0',
    cooling_fan: 'low',
    density_g_cm3: '1.270', tensile_strength_mpa: 52, heat_resistance_c: 80,
    uv_resistant: false, food_safe: false, is_abrasive: false,
    moisture_sensitivity_days: 3,
    beginner_tip: 'More heat-resistant and flexible than PLA. Stringing is common — reduce retraction speed and lower temp 5°C if you see it. Keep it dry: 3 days max open.',
  },
  {
    name: 'ABS',
    variants: ['ABS Standard'],
    nozzle_min: 230, nozzle_max: 250, nozzle_recommended: 240,
    bed_min: 100, bed_max: 110, bed_recommended: 105,
    requires_enclosure: true, dry_before_print: false,
    drying_temp_c: 80, drying_hours: '4.0',
    cooling_fan: 'none',
    density_g_cm3: '1.050', tensile_strength_mpa: 40, heat_resistance_c: 98,
    uv_resistant: false, food_safe: false, is_abrasive: false,
    moisture_sensitivity_days: 14,
    beginner_tip: 'Requires a heated enclosure and high bed temp to prevent warping and cracking. Use a PEI sheet or ABS slurry. Strong fumes — ventilate well.',
  },
  {
    name: 'ASA',
    variants: ['ASA Standard'],
    nozzle_min: 240, nozzle_max: 260, nozzle_recommended: 250,
    bed_min: 90, bed_max: 110, bed_recommended: 100,
    requires_enclosure: true, dry_before_print: false,
    drying_temp_c: 80, drying_hours: '4.0',
    cooling_fan: 'none',
    density_g_cm3: '1.070', tensile_strength_mpa: 35, heat_resistance_c: 100,
    uv_resistant: true, food_safe: false, is_abrasive: false,
    moisture_sensitivity_days: 14,
    beginner_tip: 'ABS with UV resistance. Perfect for outdoor parts, license plate frames, garden tools. Needs enclosure like ABS. Fumes are also strong.',
  },
  {
    name: 'TPU 95A',
    variants: ['TPU 95A', 'Flexible 95A'],
    nozzle_min: 220, nozzle_max: 240, nozzle_recommended: 230,
    bed_min: 30, bed_max: 60, bed_recommended: 45,
    requires_enclosure: false, dry_before_print: true,
    drying_temp_c: 55, drying_hours: '6.0',
    cooling_fan: 'high',
    density_g_cm3: '1.210', tensile_strength_mpa: 45, heat_resistance_c: 80,
    uv_resistant: false, food_safe: false, is_abrasive: false,
    moisture_sensitivity_days: 3,
    beginner_tip: 'Semi-flexible rubber-like material. Print slowly (20–30mm/s) to avoid buckling. Direct drive strongly preferred over Bowden. Great for phone cases, gaskets, wheels.',
  },
  {
    name: 'TPU 85A',
    variants: ['TPU 85A', 'Very Flexible'],
    nozzle_min: 210, nozzle_max: 230, nozzle_recommended: 220,
    bed_min: 25, bed_max: 50, bed_recommended: 40,
    requires_enclosure: false, dry_before_print: true,
    drying_temp_c: 55, drying_hours: '6.0',
    cooling_fan: 'high',
    density_g_cm3: '1.200', tensile_strength_mpa: 30, heat_resistance_c: 70,
    uv_resistant: false, food_safe: false, is_abrasive: false,
    moisture_sensitivity_days: 3,
    beginner_tip: 'Very soft and stretchy. Requires direct drive extruder. Print at 15–25mm/s. Not compatible with standard AMS/Bowden setups.',
  },
  {
    name: 'Nylon PA',
    variants: ['PA6', 'PA12', 'Nylon', 'PA'],
    nozzle_min: 240, nozzle_max: 270, nozzle_recommended: 260,
    bed_min: 70, bed_max: 90, bed_recommended: 80,
    requires_enclosure: false, dry_before_print: true,
    drying_temp_c: 70, drying_hours: '6.0',
    cooling_fan: 'low',
    density_g_cm3: '1.140', tensile_strength_mpa: 80, heat_resistance_c: 120,
    uv_resistant: false, food_safe: false, is_abrasive: false,
    moisture_sensitivity_days: 1,
    beginner_tip: 'Extremely hygroscopic — absorbs moisture in under 24 hours and prints terribly wet. Always dry before printing. Very tough and flexible when printed right.',
  },
  {
    name: 'PC',
    variants: ['Polycarbonate', 'PC Standard'],
    nozzle_min: 260, nozzle_max: 310, nozzle_recommended: 280,
    bed_min: 90, bed_max: 120, bed_recommended: 110,
    requires_enclosure: true, dry_before_print: true,
    drying_temp_c: 80, drying_hours: '8.0',
    cooling_fan: 'none',
    density_g_cm3: '1.200', tensile_strength_mpa: 65, heat_resistance_c: 145,
    uv_resistant: false, food_safe: false, is_abrasive: false,
    moisture_sensitivity_days: 1,
    beginner_tip: 'Extreme heat resistance. Requires very high nozzle temp — make sure your printer supports it. Hardened steel nozzle recommended. Enclosure is mandatory.',
  },
  {
    name: 'Silk PLA',
    variants: ['Silk', 'Silk PLA', 'Galaxy'],
    nozzle_min: 200, nozzle_max: 230, nozzle_recommended: 220,
    bed_min: 55, bed_max: 65, bed_recommended: 60,
    requires_enclosure: false, dry_before_print: false,
    drying_temp_c: null, drying_hours: null,
    cooling_fan: 'high',
    density_g_cm3: '1.240', tensile_strength_mpa: 45, heat_resistance_c: 55,
    uv_resistant: false, food_safe: false, is_abrasive: false,
    moisture_sensitivity_days: 7,
    beginner_tip: 'Shiny metallic-looking finish for decorative prints. Same settings as PLA+. Slightly more brittle — not for functional parts. Makes great display models.',
  },
  {
    name: 'Matte PLA',
    variants: ['Matte', 'Matte PLA'],
    nozzle_min: 200, nozzle_max: 225, nozzle_recommended: 210,
    bed_min: 50, bed_max: 65, bed_recommended: 55,
    requires_enclosure: false, dry_before_print: false,
    drying_temp_c: null, drying_hours: null,
    cooling_fan: 'high',
    density_g_cm3: '1.240', tensile_strength_mpa: 48, heat_resistance_c: 58,
    uv_resistant: false, food_safe: false, is_abrasive: false,
    moisture_sensitivity_days: 7,
    beginner_tip: 'Smooth non-reflective finish that hides layer lines well. Great for cosplay props, vases, and display prints. Slightly lower temp than standard PLA.',
  },
  {
    name: 'PLA-CF',
    variants: ['PLA Carbon Fiber', 'PLA CF'],
    nozzle_min: 210, nozzle_max: 230, nozzle_recommended: 220,
    bed_min: 55, bed_max: 65, bed_recommended: 60,
    requires_enclosure: false, dry_before_print: false,
    drying_temp_c: null, drying_hours: null,
    cooling_fan: 'high',
    density_g_cm3: '1.200', tensile_strength_mpa: 65, heat_resistance_c: 65,
    uv_resistant: false, food_safe: false, is_abrasive: true,
    moisture_sensitivity_days: 7,
    beginner_tip: 'Carbon fiber particles make this abrasive — brass nozzle will wear out fast. Use hardened steel or ruby. Stiffer and lighter than standard PLA. Great for RC parts.',
  },
  {
    name: 'PETG-CF',
    variants: ['PETG Carbon Fiber', 'PETG CF'],
    nozzle_min: 240, nozzle_max: 260, nozzle_recommended: 250,
    bed_min: 70, bed_max: 90, bed_recommended: 80,
    requires_enclosure: false, dry_before_print: true,
    drying_temp_c: 65, drying_hours: '4.0',
    cooling_fan: 'low',
    density_g_cm3: '1.230', tensile_strength_mpa: 70, heat_resistance_c: 90,
    uv_resistant: false, food_safe: false, is_abrasive: true,
    moisture_sensitivity_days: 3,
    beginner_tip: 'Abrasive — use hardened steel nozzle. Better layer adhesion and heat resistance than PLA-CF. Great for functional engineering parts.',
  },
  {
    name: 'PAHT-CF',
    variants: ['PA-HT CF', 'Nylon HT CF', 'PAHT CF'],
    nozzle_min: 270, nozzle_max: 300, nozzle_recommended: 285,
    bed_min: 80, bed_max: 110, bed_recommended: 95,
    requires_enclosure: true, dry_before_print: true,
    drying_temp_c: 80, drying_hours: '8.0',
    cooling_fan: 'none',
    density_g_cm3: '1.200', tensile_strength_mpa: 100, heat_resistance_c: 180,
    uv_resistant: false, food_safe: false, is_abrasive: true,
    moisture_sensitivity_days: 1,
    beginner_tip: 'High-temperature nylon with carbon fiber. Extremely strong and heat-resistant. Requires enclosure, hardened nozzle, and thorough drying. Advanced material.',
  },
  {
    name: 'PVA',
    variants: ['PVA Support', 'PVA+'],
    nozzle_min: 185, nozzle_max: 200, nozzle_recommended: 195,
    bed_min: 45, bed_max: 60, bed_recommended: 50,
    requires_enclosure: false, dry_before_print: true,
    drying_temp_c: 45, drying_hours: '4.0',
    cooling_fan: 'high',
    density_g_cm3: '1.230', tensile_strength_mpa: 35, heat_resistance_c: 55,
    uv_resistant: false, food_safe: false, is_abrasive: false,
    moisture_sensitivity_days: 1,
    beginner_tip: 'Water-soluble support material — pairs with PLA. Print in a second extruder. Dissolve in warm water (2–6 hours). Absorbs moisture instantly — store vacuum-sealed.',
  },
  {
    name: 'BVOH',
    variants: ['BVOH Support'],
    nozzle_min: 195, nozzle_max: 210, nozzle_recommended: 200,
    bed_min: 45, bed_max: 60, bed_recommended: 50,
    requires_enclosure: false, dry_before_print: true,
    drying_temp_c: 45, drying_hours: '4.0',
    cooling_fan: 'high',
    density_g_cm3: '1.230', tensile_strength_mpa: 30, heat_resistance_c: 55,
    uv_resistant: false, food_safe: false, is_abrasive: false,
    moisture_sensitivity_days: 1,
    beginner_tip: 'Faster-dissolving alternative to PVA, compatible with PETG and ABS support interfaces. More expensive but dissolves in 30–60 minutes.',
  },
  {
    name: 'HIPS',
    variants: ['HIPS', 'High Impact Polystyrene'],
    nozzle_min: 220, nozzle_max: 240, nozzle_recommended: 230,
    bed_min: 90, bed_max: 110, bed_recommended: 100,
    requires_enclosure: true, dry_before_print: false,
    drying_temp_c: null, drying_hours: null,
    cooling_fan: 'none',
    density_g_cm3: '1.050', tensile_strength_mpa: 35, heat_resistance_c: 95,
    uv_resistant: false, food_safe: false, is_abrasive: false,
    moisture_sensitivity_days: 14,
    beginner_tip: 'Limonene-soluble support for ABS prints. Requires enclosure and high bed temp. Dissolve spent supports in D-limonene. Strong fumes — ventilate.',
  },
  {
    name: 'PP',
    variants: ['Polypropylene', 'PP Standard'],
    nozzle_min: 220, nozzle_max: 250, nozzle_recommended: 235,
    bed_min: 85, bed_max: 100, bed_recommended: 90,
    requires_enclosure: true, dry_before_print: false,
    drying_temp_c: null, drying_hours: null,
    cooling_fan: 'low',
    density_g_cm3: '0.900', tensile_strength_mpa: 35, heat_resistance_c: 105,
    uv_resistant: false, food_safe: true, is_abrasive: false,
    moisture_sensitivity_days: 30,
    beginner_tip: 'Chemically resistant, food-safe (check brand certification), and very light. Notoriously poor bed adhesion — use PP-specific tape or glue stick. Warps badly without enclosure.',
  },
  {
    name: 'Wood-fill PLA',
    variants: ['Wood Fill', 'Woodfill', 'Bambu Wood'],
    nozzle_min: 195, nozzle_max: 220, nozzle_recommended: 205,
    bed_min: 50, bed_max: 65, bed_recommended: 55,
    requires_enclosure: false, dry_before_print: false,
    drying_temp_c: null, drying_hours: null,
    cooling_fan: 'high',
    density_g_cm3: '1.150', tensile_strength_mpa: 30, heat_resistance_c: 55,
    uv_resistant: false, food_safe: false, is_abrasive: true,
    moisture_sensitivity_days: 7,
    beginner_tip: 'Wood particles make it abrasive — use hardened steel nozzle. Can be sanded and stained like real wood. Print slowly (30–40mm/s) to avoid clogging.',
  },
]

async function seedMaterials() {
  console.log('Seeding material reference data…')

  for (const mat of MATERIALS) {
    await db
      .insert(materialReference)
      .values({
        name: mat.name,
        variants: mat.variants,
        nozzle_min: mat.nozzle_min,
        nozzle_max: mat.nozzle_max,
        nozzle_recommended: mat.nozzle_recommended,
        bed_min: mat.bed_min,
        bed_max: mat.bed_max,
        bed_recommended: mat.bed_recommended,
        requires_enclosure: mat.requires_enclosure,
        dry_before_print: mat.dry_before_print,
        drying_temp_c: mat.drying_temp_c,
        drying_hours: mat.drying_hours,
        cooling_fan: mat.cooling_fan,
        density_g_cm3: mat.density_g_cm3,
        tensile_strength_mpa: mat.tensile_strength_mpa,
        heat_resistance_c: mat.heat_resistance_c,
        uv_resistant: mat.uv_resistant,
        food_safe: mat.food_safe,
        is_abrasive: mat.is_abrasive,
        moisture_sensitivity_days: mat.moisture_sensitivity_days,
        beginner_tip: mat.beginner_tip,
      })
      .onConflictDoUpdate({
        target: materialReference.name,
        set: {
          nozzle_min: mat.nozzle_min,
          nozzle_max: mat.nozzle_max,
          nozzle_recommended: mat.nozzle_recommended,
          bed_min: mat.bed_min,
          bed_max: mat.bed_max,
          bed_recommended: mat.bed_recommended,
          requires_enclosure: mat.requires_enclosure,
          dry_before_print: mat.dry_before_print,
          drying_temp_c: mat.drying_temp_c,
          drying_hours: mat.drying_hours,
          cooling_fan: mat.cooling_fan,
          density_g_cm3: mat.density_g_cm3,
          tensile_strength_mpa: mat.tensile_strength_mpa,
          heat_resistance_c: mat.heat_resistance_c,
          uv_resistant: mat.uv_resistant,
          food_safe: mat.food_safe,
          is_abrasive: mat.is_abrasive,
          moisture_sensitivity_days: mat.moisture_sensitivity_days,
          beginner_tip: mat.beginner_tip,
        },
      })
    console.log(`  ✓ ${mat.name}`)
  }

  console.log(`Done — ${MATERIALS.length} materials seeded.`)
  process.exit(0)
}

seedMaterials().catch((e) => { console.error(e); process.exit(1) })
