CREATE TABLE "material_reference" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"variants" text[],
	"nozzle_min" integer,
	"nozzle_max" integer,
	"nozzle_recommended" integer,
	"bed_min" integer,
	"bed_max" integer,
	"bed_recommended" integer,
	"requires_enclosure" boolean DEFAULT false,
	"dry_before_print" boolean DEFAULT false,
	"drying_temp_c" integer,
	"drying_hours" numeric(4, 1),
	"cooling_fan" text DEFAULT 'high',
	"density_g_cm3" numeric(5, 3),
	"tensile_strength_mpa" integer,
	"heat_resistance_c" integer,
	"uv_resistant" boolean DEFAULT false,
	"food_safe" boolean DEFAULT false,
	"is_abrasive" boolean DEFAULT false,
	"moisture_sensitivity_days" integer,
	"beginner_tip" text,
	CONSTRAINT "material_reference_name_unique" UNIQUE("name")
);
